### ISSUE TITLE
Call to undefined method after artisan optimize

### ISSUE THREAD

**Issue by renfordt** [ralphjsmit/laravel-seo#65]
After calling `php artisan optimize` I get always the following error:

```
Call to undefined method RalphJSmit\Laravel\SEO\Support\SEOData::__set_state() {"exception":"[object] (Error(code: 0): Call to undefined method RalphJSmit\\Laravel\\SEO\\Support\\SEOData::__set_state() at /bootstrap/cache/routes-v7.php:7551)
[stacktrace]
#0 /var/www/clients/client1/web210/web/releases/20240307103309/vendor/laravel/framework/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php(108): require()
#1 /var/www/clients/client1/web210/web/releases/20240307103309/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1073): Illuminate\\Foundation\\Support\\Providers\\RouteServiceProvider->Illuminate\\Foundation\\Support\\Providers\\{closure}()
#2 /var/www/clients/client1/web210/web/releases/20240307103309/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1016): Illuminate\\Foundation\\Application->fireAppCallbacks()
#3 /var/www/clients/client1/web210/web/releases/20240307103309/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#4 /var/www/clients/client1/web210/web/releases/20240307103309/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(263): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
#5 /var/www/clients/client1/web210/web/releases/20240307103309/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(186): Illuminate\\Foundation\\Application->bootstrapWith()
#6 /var/www/clients/client1/web210/web/releases/20240307103309/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#7 /var/www/clients/client1/web210/web/releases/20240307103309/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#8 /var/www/clients/client1/web210/web/releases/20240307103309/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#9 {main}
"} 
```

It seems that something in the cache is not working properly:
```
at bootstrap/cache/routes-v7.php:7599
    7595▕         'view' => 'faq',
    7596▕         'data' => 
    7597▕         array (
    7598▕           'SEOData' => 
  ➜ 7599▕           \RalphJSmit\Laravel\SEO\Support\SEOData::__set_state(array(
 
```

This has been verified on production server and also in development environment.

If you need further information don't hesitate to contact me.

**Comment by ralphjsmit** [comment]
Hi @renfordt, thank you for your message! I have just tried caching routes where the SEOData is instantiated, which worked for me. Can you please share your `Route::xxx()` declaration that you used and where you used the SEOData object?

**Comment by renfordt** [comment]
My Routes are mainly like these:
```php
Route::resource('/teams', TeamController::class);
```

or 

```php
Route::view('/FAQ', 'faq', [
    'SEOData' => new SEOData(
        title: 'FAQ',
        description: 'some text',
    ),
])->name('FAQ');
```

Last one seems like the issue according to my logs.
